<?php

	/**
	 * Autogenerated module TracPlugin
	 *
	 * @author Matheus B. Campos & Bruno Paiva
	 * @version 0.1
	 * @license http://www.opensource.org/licenses/mozilla1.1.php Mozilla Public License 1.1 (MPL 1.1)
	 * @package tracplugin
	 * @subpackage core
	 */

	/**
	 * Autogenerated module TracPlugin
	 *
	 * @package tracplugin
	 * @subpackage core
	 *
	 * @Table(name="TBGModulesTable")
	 */
	class TracPlugin extends TBGModule
	{

		protected $_longname = 'Trac Plugin';

		protected $_description = 'Trac Plugin - Integrating The Bug Genie and Trac.';

		protected $_module_config_title = 'Trac plugin';

		protected $_module_config_description = 'Set up the TracPlugin module from this section';

		protected $_has_config_settings = true;

		protected $_module_version = '0.1';

		/**
		 * Return an instance of this module
		 * Convenience method to provide better code completion
		 *
		 * @return TracPlugin
		 */
		public static function getModule()
		{
			return TBGContext::getModule('tracplugin');
		}

		protected function _initialize()
		{
		}

		protected function _addListeners()
		{
			TBGEvent::listen('core', 'TBGIssue::createNew', array($this, 'listen_issue_create'));
		}

		protected function _addRoutes()
		{
			$this->addRoute('tracplugin_index', '/tracplugin', 'index');
			$this->addRoute('tracplugin_setstatus', '/tracplugin/:project_key/:issue_id/set/:status_id', 'setStatus');
		}

		protected function _install($scope)
		{
			TBGContext::getRouting()->addRoute('tracplugin_index', '/tracplugin', 'tracplugin', 'index');
		}

		protected function _loadFixtures($scope)
		{
		}

		protected function _uninstall()
		{
			parent::_uninstall();
		}

		public function getRoute()
		{
			return TBGContext::getRouting()->generate('tracplugin_index');
		}

		public function listen_issue_create(TBGEvent $event)
		{
			// TODO Create Bug Report on Trac.
			$issue = $event->getSubject();
			error_log($issue->getID() . PHP_EOL, 3, "/var/tmp/my-errors.log");
		}
	}

